server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/league_db
    username: postgres
    password: 50465890
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
    show-sql: true

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.xml